### ISSUE TITLE
followme exception when stack does not exist

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/cli#27]
```
(madcore) followme
2017-01-15 13:28:52,061 [DEBUG] madcore: prepare_to_run_command Followme
2017-01-15 13:28:52,061 [INFO] madcore: Already configured.
2017-01-15 13:28:52,427 [INFO] madcore.cmds.followme: Core Followme: Your public IP detected as: 90.203.250.106
2017-01-15 13:28:52,724 [ERROR] madcore.cmds.followme: An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id MADCORE-FollowMe does not exist
2017-01-15 13:28:52,724 [ERROR] madcore: 'NoneType' object has no attribute '__getitem__'
2017-01-15 13:28:52,724 [DEBUG] madcore: Got an error: 'NoneType' object has no attribute '__getitem__'
2017-01-15 13:28:52,725 [DEBUG] madcore: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cliff/display.py", line 112, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/madcore-0.1.60+gdf6e139-py2.7.egg/madcore/cmds/followme.py", line 40, in take_action
    previous_parameters = stack['Parameters']
TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by botzill** [comment]
Already fixed in the PR https://github.com/madcore-ai/cli/pull/24
