### ISSUE TITLE
followme row has incorrect number of values

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/cli#29]
Last step of FollowMe command should be a table showing OLD and NEW address. Something must have changed because that table is now showing an exception.

```
AWS::CloudFormation::Stack               UPDATE_COMPLETE
2017-01-16 18:12:57,774 [ERROR] madcore: Row has incorrect number of values, (actual) 13!=3 (expected)
2017-01-16 18:12:57,774 [DEBUG] madcore: Got an error: Row has incorrect number of values, (actual) 13!=3 (expected)
2017-01-16 18:12:57,811 [DEBUG] madcore: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cliff-2.4.0-py2.7.egg/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/site-packages/cliff-2.4.0-py2.7.egg/cliff/display.py", line 113, in run
    self.produce_output(parsed_args, column_names, data)
  File "/usr/local/lib/python2.7/site-packages/madcore-0.1.70+gca0c294-py2.7.egg/madcore/libs/cloudformation.py", line 25, in produce_output
    self.formatter.emit_list(column_names, data, Stdout(), parsed_args)
  File "/usr/local/lib/python2.7/site-packages/cliff-2.4.0-py2.7.egg/cliff/formatters/table.py", line 92, in emit_list
    self.add_rows(x, column_names, data)
  File "/usr/local/lib/python2.7/site-packages/cliff-2.4.0-py2.7.egg/cliff/formatters/table.py", line 79, in add_rows
    table.add_row(_format_row(first_row))
  File "/usr/local/lib/python2.7/site-packages/prettytable.py", line 818, in add_row
    raise Exception("Row has incorrect number of values, (actual) %d!=%d (expected)" %(len(row),len(self._field_names)))
Exception: Row has incorrect number of values, (actual) 13!=3 (expected)
```

**Comment by botzill** [comment]
Seems to work ok now.
