### ISSUE TITLE
`madcore configure` fails if bitbucket user has no teams

### ISSUE THREAD

**Issue by amkartashov** [madcore-ai/cli#38]
```
2017-01-18 23:19:54,199 [INFO] madcore.configure: Check if user already exists.
Input madcore password:
2017-01-18 23:20:05,151 [INFO] madcore.configure: Login user(automatically)
2017-01-18 23:20:06,259 [ERROR] madcore.configure: User not found: gorilych@gmail.com
2017-01-18 23:20:06,259 [INFO] madcore.configure: User does not exists, create: 'gorilych@gmail.com'
2017-01-18 23:20:07,215 [ERROR] madcore: options should not be an empty list
Traceback (most recent call last):
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/cliff/display.py", line 112, in run
    column_names, data = self.take_action(parsed_args)
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/madcore/cmds/configure.py", line 71, in take_action
    config_results = configure.take_action(parsed_args)
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/madcore/configure.py", line 409, in take_action
    self.configure_user_registration()
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/madcore/configure.py", line 348, in configure_user_registration
    selected_team = self.single_prompt('team', options=teams, prompt='Select bitbucket team')
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/madcore/configure.py", line 34, in single_prompt
    return questionnaire.run()
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/questionnaire/__init__.py", line 124, in run
    if not self.ask_questions():
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/questionnaire/__init__.py", line 135, in ask_questions
    if not self.ask_question(question):
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/questionnaire/__init__.py", line 146, in ask_question
    self.answers[q.key], back = q.prompter(prompt, **q.prompter_args)
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/questionnaire/prompters.py", line 35, in single
    picker = Picker(options, title=prompt, indicator='=>')
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/pick/__init__.py", line 26, in __init__
    raise ValueError('options should not be an empty list')
ValueError: options should not be an empty list
2017-01-18 23:20:07,217 [DEBUG] madcore: Got an error: options should not be an empty list
2017-01-18 23:20:07,218 [DEBUG] madcore: Traceback (most recent call last):
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/cliff/display.py", line 112, in run
    column_names, data = self.take_action(parsed_args)
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/madcore/cmds/configure.py", line 71, in take_action
    config_results = configure.take_action(parsed_args)
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/madcore/configure.py", line 409, in take_action
    self.configure_user_registration()
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/madcore/configure.py", line 348, in configure_user_registration
    selected_team = self.single_prompt('team', options=teams, prompt='Select bitbucket team')
  File "/home/me/tmp/madcore/env/local/lib/python2.7/site-packages/madcore/configure.py", line 34, in single_prompt

```

**Comment by botzill** [comment]
Fixed in the latest commit https://github.com/madcore-ai/cli/commit/c62a3cf3b0b69c468a9dae9ea60d61f039ed96b7

**Comment by styk-tv** [comment]
This is showing up back on 0.3.7

```
2017-01-20 17:34:21,788 [DEBUG] madcore.configure: Connect to bitbucket and get information...
2017-01-20 17:34:23,425 [INFO] madcore.configure: Check if user already exists.
Input madcore password: 
2017-01-20 17:36:10,321 [INFO] madcore.configure: Login user(automatically)
2017-01-20 17:36:11,204 [ERROR] madcore.configure: User not found: user@email
2017-01-20 17:36:11,205 [INFO] madcore.configure: User does not exists, create: 'user@email'
2017-01-20 17:36:12,202 [ERROR] madcore: options should not be an empty list
2017-01-20 17:36:12,203 [DEBUG] madcore: Got an error: options should not be an empty list
```

**Comment by styk-tv** [comment]
Restart after failed team (so no domain saved)

```
(madcore) q
gsa@gsa:~$ madcore


Madcore Core CLI - Deep Learning & Machine Intelligence Infrastructure Controller
v0.3.7 Licensed under MIT (c) 2015-2017 Madcore Ltd - https://madcore.ai

2017-01-20 17:42:32,861 [DEBUG] madcore: initialize_app
2017-01-20 17:42:32,862 [INFO] madcore: Already configured.
(madcore)
```

**Comment by botzill** [comment]
OK, fixed this case. If user is not yet logged in and we try to execute a command, then configuration will be triggered.
