### ISSUE TITLE
madcore initialisation fails

### ISSUE THREAD

**Issue by nands** [madcore-ai/cli#40]
Steps to reproduce 

Remove all .madcore directories
pip uninstall madcore
pip install madcore (Installs version madcore-0.3.6)
madcore
<say yes to configure>

Error ->

2017-01-18 21:33:01,712 [INFO] madcore.configure: User Registration
2017-01-18 21:33:01,713 [INFO] madcore.configure: Start user registration.
2017-01-18 21:33:03,484 [ERROR] madcore: An error occurred (NotAuthorizedException) when calling the GetId operation: Access to IdentityPool 'eu-west-1:964ea940-a8e6-44a5-a88b-c510cfe487d7' is forbidden.
2017-01-18 21:33:03,484 [DEBUG] madcore: Got an error: An error occurred (NotAuthorizedException) when calling the GetId operation: Access to IdentityPool 'eu-west-1:964ea940-a8e6-44a5-a88b-c510cfe487d7' is forbidden.
2017-01-18 21:33:03,486 [DEBUG] madcore: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/site-packages/cliff/display.py", line 112, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/local/lib/python2.7/site-packages/madcore/cmds/configure.py", line 71, in take_action
    config_results = configure.take_action(parsed_args)
  File "/usr/local/lib/python2.7/site-packages/madcore/configure.py", line 409, in take_action
    self.configure_user_registration()
  File "/usr/local/lib/python2.7/site-packages/madcore/configure.py", line 306, in configure_user_registration
    aws_lambda = AwsLambda()
  File "/usr/local/lib/python2.7/site-packages/madcore/libs/aws.py", line 46, in __init__
    self.lambda_client_no_auth = self.create_aws_lambda_client()
  File "/usr/local/lib/python2.7/site-packages/madcore/libs/aws.py", line 68, in create_aws_lambda_client
    identity_id = self.get_identity_id()
  File "/usr/local/lib/python2.7/site-packages/madcore/libs/aws.py", line 60, in get_identity_id
    IdentityPoolId=self.identity_pool_id,
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (NotAuthorizedException) when calling the GetId operation: Access to IdentityPool 'eu-west-1:964ea940-a8e6-44a5-a88b-c510cfe487d7' is forbidden.

**Comment by botzill** [comment]
This issue was fixed by https://github.com/madcore-ai/cli/commit/4ec94ad4ae0355ccf9c708484d8838ae32a80e45. 

@nands Please confirm that is working in your case.
