### ISSUE TITLE
Read domain when repo not cloned

### ISSUE THREAD

**Issue by botzill** [madcore-ai/cli#79]
```
2017-02-06 14:26:31,110 [ERROR] madcore: object of type 'NoneType' has no len()
2017-02-06 14:26:31,111 [DEBUG] madcore: Got an error: object of type 'NoneType' has no len()
2017-02-06 14:26:31,118 [DEBUG] madcore: Traceback (most recent call last):
  File "/Users/polfilm/builds/venv/lib/python2.7/site-packages/cliff-2.4.0-py2.7.egg/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/Users/polfilm/builds/venv/lib/python2.7/site-packages/cliff-2.4.0-py2.7.egg/cliff/display.py", line 112, in run
    column_names, data = self.take_action(parsed_args)
  File "/Users/polfilm/builds/venv/lib/python2.7/site-packages/madcore-0.4.2.17+gb2a7534-py2.7.egg/madcore/cmds/configure.py", line 114, in take_action
    configure.take_action(parsed_args)
  File "/Users/polfilm/builds/venv/lib/python2.7/site-packages/madcore-0.4.2.17+gb2a7534-py2.7.egg/madcore/configure.py", line 452, in take_action
    self.configure_user_registration()
  File "/Users/polfilm/builds/venv/lib/python2.7/site-packages/madcore-0.4.2.17+gb2a7534-py2.7.egg/madcore/configure.py", line 402, in configure_user_registration
    prompt='Select madcore domain')
  File "/Users/polfilm/builds/venv/lib/python2.7/site-packages/madcore-0.4.2.17+gb2a7534-py2.7.egg/madcore/base.py", line 115, in single_prompt
    return questionnaire.run()
  File "build/bdist.macosx-10.10-x86_64/egg/questionnaire/__init__.py", line 124, in run
    if not self.ask_questions():
  File "build/bdist.macosx-10.10-x86_64/egg/questionnaire/__init__.py", line 135, in ask_questions
    if not self.ask_question(question):
  File "/Users/polfilm/builds/venv/lib/python2.7/site-packages/madcore-0.4.2.17+gb2a7534-py2.7.egg/madcore/libs/input_questions.py", line 80, in ask_question
    answer, back = q.prompter(prompt, jinja_params=self.jinja_params, **q.prompter_args)
  File "build/bdist.macosx-10.10-x86_64/egg/questionnaire/prompters.py", line 35, in single
    picker = Picker(options, title=prompt, indicator='=>')
  File "build/bdist.macosx-10.10-x86_64/egg/pick/__init__.py", line 25, in __init__
    if len(options) == 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by botzill** [comment]
Fixed by #81
