### ISSUE TITLE
setup.py missing jenkins

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/cli#9]
```
polfilm@petersmacbook2:~/builds$ madcore
Traceback (most recent call last):
  File "/usr/local/bin/madcore", line 9, in <module>
    load_entry_point('madcore==0.3', 'console_scripts', 'madcore')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/madcore-0.3-py2.7.egg/madcore/madcore.py", line 10, in <module>
    import configure
  File "/usr/local/lib/python2.7/site-packages/madcore-0.3-py2.7.egg/madcore/configure.py", line 14, in <module>
    from base import MadcoreBase
  File "/usr/local/lib/python2.7/site-packages/madcore-0.3-py2.7.egg/madcore/base.py", line 10, in <module>
    from jenkins import Jenkins
```

**Comment by styk-tv** [comment]
package 'python-jenkins-

**Comment by botzill** [comment]
Fixed.
